device: cuda

# Dataset configuration
datasets:
  cifar10:
    path: ./data/cifar10
    num_classes: 10
    description: "CIFAR-10 image classification dataset with 10 classes"
  cifar100:
    path: ./data/cifar100
    num_classes: 100
    description: "CIFAR-100 image classification dataset with 100 classes"
  mnist:
    path: ./data/mnist
    num_classes: 10
    description: "MNIST handwritten digit recognition dataset with 10 classes"

selected_dataset: cifar10

model_types:
  - attention_cnn
  - resnet18
  - resnet34
  - resnet50
  - resnet101
  - resnet152
  - resnet20
  - resnet32
  - resnet44
  - resnet56
  - resnet110
  - resnet1202
  - Autoencoder

selected_model: attention_cnn

train:
  n_epochs: 5
  batch_size: 64
  lr: !!float 1e-3
  output_dir: ./ckpts
  early_stopping_patience: 10  # Number of epochs to wait before early stopping
  pretrain_epochs: 5  
  pretrain_lr: !!float 1e-3  

test:
  batch_size: 64
  ckpt_path: ckpts/cifar10/attention_cnn/latest.pth